name: portfolio

services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: "0.0.0.0"
    security_opt:
      - no-new-privileges:true
    networks:
      - web

networks:
  web:
    driver: bridge
